services:
  Slink\Settings\Domain\Provider\ConfigurationProviderInterface:
    class: Slink\Settings\Application\Service\SettingsService
    arguments:
      $configurationLocator: '@Slink\Settings\Infrastructure\Provider\ConfigurationProviderLocator'