parameters:
  supported_image_formats:
    - 'image/bmp'
    - 'image/png'
    - 'image/jpeg'
    - 'image/jpg'
    - 'image/gif'
    - 'image/webp'
    - 'image/svg+xml'
    - 'image/svg'
    - 'image/x-icon'
    - 'image/vnd.microsoft.icon'
    - 'image/x-tga'

  supports_resize: ['image/bmp', 'image/png', 'image/jpeg', 'image/jpg', 'image/webp']
  supports_strip_exif: ['image/jpeg', 'image/jpg']

services:
  Slink\Image\Domain\Service\ImageAnalyzerInterface:
    class: Slink\Image\Application\Service\ImageAnalyzer
    arguments:
      $resizableMimeTypes: '%supports_resize%'
      $stripExifMimeTypes: '%supports_strip_exif%'
