import chokidar from 'chokidar';
import fs from 'fs';
import path from 'path';

const HOOK_FILE_SUFFIX = '.hook.ts';
const MANIFEST_FILE = 'manifest.gen.ts';
const HEADER = '// AUTO-GENERATED by vite-hook-manifest. Do not edit.\n';

function readDirectories(dir: string): string[] {
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);
}

function readHookFiles(dir: string): string[] {
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(HOOK_FILE_SUFFIX))
    .map((entry) => entry.name);
}

export function isHookFile(file: string): boolean {
  return file.endsWith(HOOK_FILE_SUFFIX);
}

export function scanHookIds(dir: string): string[] {
  if (!fs.existsSync(dir)) {
    return [];
  }

  const ids = readDirectories(dir).flatMap((stage) =>
    readHookFiles(path.join(dir, stage)).map(
      (file) => `${stage}/${file.slice(0, -HOOK_FILE_SUFFIX.length)}`,
    ),
  );

  return ids.sort();
}

export function renderManifest(ids: string[]): string {
  if (ids.length === 0) {
    return `${HEADER}export type HookId = never;\n`;
  }

  const union = ids.map((id) => `  | '${id}'`).join('\n');

  return `${HEADER}export type HookId =\n${union};\n`;
}

export function writeManifest(dir: string): {
  output: string;
  changed: boolean;
} {
  const output = path.join(dir, MANIFEST_FILE);
  const content = renderManifest(scanHookIds(dir));

  if (fs.existsSync(output) && fs.readFileSync(output, 'utf-8') === content) {
    return { output, changed: false };
  }

  fs.writeFileSync(output, content);

  return { output, changed: true };
}

export function createWatcher(dir: string, usePolling: boolean) {
  return chokidar.watch(dir, {
    ignoreInitial: true,
    usePolling,
    ignored: /manifest\.gen\.ts$/,
  });
}
