services:
  slink:
    build:
        context: .
        target: prod
    image: anirdev/slink:latest
    container_name: slink
    restart: always
    environment:
      - TZ=Europe/Kyiv
      - SWOOLE_WORKER_NUM=4
      - API_ENABLED=true