name: 'Test'
description: 'Run PHPUnit tests'

runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/build-test-image

    - shell: bash
      run: |
        docker run --rm slink-test:${{ github.sha }} \
          php /services/api/vendor/bin/phpunit --configuration /services/api/phpunit.xml --no-coverage
