#!/bin/sh

if [ "$(id -u)" = "0" ]; then
  chown -R slink:slink /app
  chown -R www-data:slink /data/caddy
  chown -R redis:slink /data/redis
fi

delegate slink /usr/local/bin/init-secrets

if [ -f /app/var/data/keys/passphrase ]; then
  export JWT_PASSPHRASE=$(cat /app/var/data/keys/passphrase)
fi

if [ -f /app/var/data/keys/mercure_secret ]; then
  export MERCURE_JWT_SECRET=$(cat /app/var/data/keys/mercure_secret)
fi

if [ -f /app/var/data/keys/app_secret ]; then
  export APP_SECRET=$(cat /app/var/data/keys/app_secret)
fi

exec /init "$@"
