FROM common AS test

ARG MEMORY_LIMIT

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /services/api

RUN apk add --no-cache git unzip exiftool

COPY services/api/composer.json services/api/composer.lock ./
RUN composer install --ignore-platform-reqs --no-interaction --no-scripts

COPY --chown=www-data:www-data ./services/api .
RUN mv .env.example .env && \
    mkdir -p config/jwt && \
    openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out config/jwt/private.pem && \
    openssl pkey -in config/jwt/private.pem -pubout -out config/jwt/public.pem && \
    chmod 644 config/jwt/private.pem config/jwt/public.pem && \
    rm -rf var/functional-test && \
    mkdir -p var/functional-test && \
    chmod 777 var/functional-test

ENV APP_ENV=test \
    IMAGE_MAX_SIZE=5M

ENTRYPOINT []
