services:
  slink:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    environment:
      - ORIGIN=http://localhost:5173
      - OAUTH_VERIFY_SSL=false
    volumes:
      - ../services:/services
      - ../var:/app/var
      - ../slink:/app/slink
      - node_modules:/services/client/node_modules
    ports:
      - "8080:8080"
      - "5173:5173"
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "authentik.loc:host-gateway"
      - "authelia.loc:host-gateway"
      - "keycloak.loc:host-gateway"
      - "pocket-id.loc:host-gateway"
      - "zitadel.loc:host-gateway"

volumes:
  node_modules:
