# check=skip=InvalidDefaultArgInFrom
ARG ALPINE_VERSION
ARG COMPOSER_VERSION

FROM staging AS test-rootfs

RUN mkdir -p /rootfs/etc/apk && cp -r /apk-config/. /rootfs/etc/apk/

RUN apk add --root /rootfs --initdb --no-cache \
        git \
        unzip \
        exiftool@alpine

RUN rm -rf /rootfs/lib/apk /rootfs/etc/apk /rootfs/var/cache/apk /rootfs/var/run /rootfs/var/lock

FROM composer:${COMPOSER_VERSION} AS composer

FROM common AS test

ARG MEMORY_LIMIT

COPY --from=composer /usr/bin/composer /usr/bin/composer

WORKDIR /services/api

COPY --from=test-rootfs /rootfs/ /

COPY services/api/composer.json services/api/composer.lock ./
RUN composer install --ignore-platform-reqs --no-interaction --no-scripts

COPY --chown=www-data:www-data ./services/api .
RUN mv .env.example .env && \
    mkdir -p config/jwt && \
    openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out config/jwt/private.pem && \
    openssl pkey -in config/jwt/private.pem -pubout -out config/jwt/public.pem && \
    chmod 644 config/jwt/private.pem config/jwt/public.pem && \
    rm -rf var/functional-test && \
    mkdir -p var/functional-test && \
    chmod 777 var/functional-test

ENV APP_ENV=test \
    IMAGE_MAX_SIZE=5M

ENTRYPOINT []
