parameters:
  storage:
    provider: '%env(string:STORAGE_PROVIDER)%'
    adapter:
      local:
        dir: '%kernel.project_dir%'
      smb:
        host: '%env(string:default::SMB_HOST)%'
        share: '%env(string:default::SMB_SHARE)%'
        workgroup: '%env(string:default::SMB_WORKGROUP)%'
        username: '%env(string:default::SMB_USERNAME)%'
        password: '%env(string:default::SMB_PASSWORD)%'
  user:
    allowRegistration: true
    allowUnauthenticatedAccess: '%env(bool:USER_ALLOW_UNAUTHENTICATED_ACCESS)%'
    approvalRequired: '%env(bool:USER_APPROVAL_REQUIRED)%'
    password:
      minLength: '%env(int:USER_PASSWORD_MIN_LENGTH)%'
      requirements: '%env(int:USER_PASSWORD_REQUIREMENTS)%'
  image:
    maxSize: '%env(string:IMAGE_MAX_SIZE)%'
    stripExifMetadata: '%env(bool:IMAGE_STRIP_EXIF_METADATA)%'