name: 'Build Test Docker Image'
description: 'Builds a Docker image for testing and linting'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Load Test Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile
        target: test
        load: true
        tags: slink-test:${{ github.sha }}
        cache-from: type=gha,scope=test-build
        cache-to: type=gha,scope=test-build
