name: 'Build Test Docker Image'
description: 'Builds a Docker image for testing and linting'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Load Test Docker image
      uses: docker/bake-action@v6
      with:
        source: .
        targets: test
        load: true
        set: |
          test.tags=slink-test:${{ github.sha }}
          *.cache-from=type=gha,scope=test-build
          *.cache-to=type=gha,scope=test-build
