// AUTO-GENERATED by vite-hook-manifest. Do not edit.
export type HookId =
  | 'locals/apiClient'
  | 'locals/apiProxy'
  | 'locals/cookieManager'
  | 'locals/cookieSettings'
  | 'locals/globalSettings'
  | 'locals/locale'
  | 'locals/uploadPolicy'
  | 'locals/userLocale'
  | 'locals/userPreferences'
  | 'render/locale'
  | 'render/mode'
  | 'render/theme'
  | 'render/themeColor'
  | 'request/responseHeaders'
  | 'request/wellKnown'
  | 'response/htmlCache'
  | 'response/linkHeader';
