// AUTO-GENERATED by vite-hook-manifest. Do not edit.
export type HookId =
  | 'locals/apiClient'
  | 'locals/apiProxy'
  | 'locals/cookies'
  | 'locals/globalSettings'
  | 'locals/settings'
  | 'locals/uploadPolicy'
  | 'locals/userLocale'
  | 'locals/userPreferences'
  | 'locals/userTheme'
  | 'render/locale'
  | 'render/shell'
  | 'request/responseHeaders'
  | 'request/wellKnown'
  | 'response/htmlCache'
  | 'response/linkHeader';
