name: '[frontend] CI'

permissions:
  contents: write

on:
  push:
    branches: [main, develop]
    paths:
      - 'services/client/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: './services/client/yarn.lock'

      - name: Install dependencies
        run: yarn --cwd ./services/client install --frozen-lockfile

      - name: Run ESLint
        run: yarn --cwd ./services/client run lint

      - name: Type check
        run: yarn --cwd ./services/client run check
