name: '[frontend] CI'

permissions:
  contents: write

on:
  push:
    branches: [main, develop]
    paths:
      - 'services/client/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

jobs:
  format:
    name: Format Codebase
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prettier Format Check
        uses: ./.github/actions/prettier
